name: Flutter Android Build

on:
    push:
        tags:
        - '*'

jobs:
    build_android:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v2
              with:
                  distribution: "zulu"
                  java-version: "17"
            - uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.3.10"
            - run: flutter pub get
            - run: flutter pub run build_runner build --delete-conflicting-outputs
            # - run: flutter test
            - run: flutter build apk --release
            - run: flutter build appbundle --release
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                files: |
                    build/app/outputs/flutter-apk/app-release.apk
                    build/app/outputs/bundle/release/app-release.aab
